# Project information
site_name: 'Python'
site_author: 'Jacques Dainat et al.'
site_url: 'https://southgreenplatform.github.io/training_python/'
site_description: Workshop on Tools for Reproducible Research
site_dir: public # When you build your site, all of the files are written to the directory assigned to the site_dir configuration option (defaults to "site")

# Repository
repo_name: 'training_python'
repo_url: 'https://github.com/SouthGreenPlatform/training_python'
edit_uri: edit/main/docs/ # Allow to replace edit/master/docs use by default

# Configuration
theme:
  name: material
  logo: pages/img/southgreen.png # logo top left page
  search_index_only: true
  include_search_page: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections # collapse subsections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate # remove table of content on the right side
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: docs
  - attr_list
  - tables
  - toc:
    #  toc_depth: 3
      permalink: '#'

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - macros

# Customization
extra:
#  homepage:  # Page displayed when clicking the logo
  history_buttons: false
  # --- set whole scope variables ---
  contact: https://www.southgreen.fr/contact
  institute: SouthGreen
  color_table_header: "#333a99"

# page tree
nav:
    - Home: index.md
    - Tutorials:
        - Introduction : pages/introduction.md
        - Variables : pages/variables.md
        - Fonctions : pages/fonctions.md
        - Classes : pages/classes.md
        - Pratique 1 : pages/pratiques/pratique1.md
        - Structures conditionnelles: pages/structures_conditionnelles.md
        - Listes: pages/listes.md
        - Boucles: pages/boucles.md
        - Pratique 3 : pages/pratiques/pratique3.md
        - Pratique 4 : pages/pratiques/pratique4.md
        - Modules : pages/modules.md
        - Passage d'arguments : pages/passage_arguments.md
        - Fichiers : pages/fichiers.md
        - Manipulation des chaînes de caractères : pages/manipulation_des_chaines_de_caracteres.md
        - Pratique 6 : pages/pratiques/pratique6.md
        - Dictionnaires : pages/dictionnaires.md
        - Biopython : pages/biopython.md
        - Biopython API: pages/biopython_api.md
        - Subprocess : pages/subprocess.md
        - Vos propres fonctions : pages/vos_propres_fonctions.md
        - Modules utiles : pages/modules_utiles.md
        - Panda : pages/panda.md
        - Ending : pages/ending.md
