name: lectures

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the main branch
on:
  push:
    paths:
      - 'lectures/*/*.Rmd'
      - 'lectures/*/*.ipynb'
      - '.github/workflows/lectures.yml'
  pull_request:
    paths:
      - 'lectures/*/*.Rmd'
      - 'lectures/*/*.ipynb'
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: lecture-env
        environment-file: docs/lectures/environment.yml
        installer-url: https://repo.continuum.io/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh
        auto-activate-base: false
    - name: Render lectures
      run: |
        snakemake -d lectures/ -s lectures/Snakefile -j 1
